#!/usr/bin/env node
// Bundles src/ into a single self-contained index.html.
//
// Inputs:
//   src/template.html  with {{STYLES}} and {{SCRIPT}} markers
//   src/styles.css
//   src/stubs/prg_loader.bin
//   src/stubs/prg_loader_compressed.bin
//   src/<module>.js  in MODULE_ORDER
//
// Output:
//   index.html  (committed; CI verifies this is in sync with src/)
//
// The bundle is one <script type="module"> body. src/*.js files use ESM
// `export`/`import` so Vitest can import them directly; the build strips
// those keywords because everything ends up in a single module scope.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(fileURLToPath(import.meta.url));
const SRC = join(ROOT, 'src');
const STUBS = join(SRC, 'stubs');

// Order matters: each module may reference identifiers from the modules
// listed above it. Modules that don't exist yet are skipped (early epics).
//
// prg-loader.js is generated by this script from src/stubs/*.bin and
// committed. Listing it here makes it part of the same single-module
// scope so cart-writer.js can `import { PRG_LOADER } from './prg-loader.js'`
// during Vitest runs while the build strips the import for the bundle.
const MODULE_ORDER = [
  'lzss.js',
  'prg-loader.js',
  'prg.js',
  'gemdos.js',
  'cart-writer.js',
  'classic-mode.js',
  'help-content.js',
  'ui.js',
];

function readText(path) {
  return readFileSync(path, 'utf8');
}

function readBytes(path) {
  return readFileSync(path);
}

function bytesToUint8ArrayLiteral(name, bytes, withExport) {
  const lines = [];
  for (let i = 0; i < bytes.length; i += 16) {
    const row = [];
    for (let j = i; j < Math.min(i + 16, bytes.length); j++) {
      row.push('0x' + bytes[j].toString(16).padStart(2, '0').toUpperCase());
    }
    lines.push('  ' + row.join(', ') + (i + 16 < bytes.length ? ',' : ''));
  }
  const prefix = withExport ? 'export const' : 'const';
  return `${prefix} ${name} = new Uint8Array([\n${lines.join('\n')}\n]);\n`;
}

// Regenerate src/prg-loader.js from the canonical .bin files. Always
// overwrites (with deterministic content) so a stale prg-loader.js is
// caught by the same `git diff --exit-code` step that catches a stale
// index.html.
function regeneratePrgLoaderJs() {
  const header =
    '// AUTOGENERATED by build.mjs from src/stubs/*.bin — do not hand-edit.\n' +
    '// To update: replace the .bin files (frozen snapshots from upstream\n' +
    '// atarist-USM), run `npm run build`, commit the regenerated file.\n\n';
  const loader = readBytes(join(STUBS, 'prg_loader.bin'));
  const loaderZ = readBytes(join(STUBS, 'prg_loader_compressed.bin'));
  const body =
    bytesToUint8ArrayLiteral('PRG_LOADER', loader, /*withExport*/ true) +
    '\n' +
    bytesToUint8ArrayLiteral('PRG_LOADER_COMPRESSED', loaderZ, /*withExport*/ true);
  writeFileSync(join(SRC, 'prg-loader.js'), header + body);
}

// Naive ESM-to-flat-script transform. We assume all src/*.js files end up
// concatenated into one module scope, so `export` and `import` statements
// against sibling files are not needed at runtime — they're scaffolding
// for Vitest.
function stripEsm(source) {
  let out = source;
  // Drop static imports from sibling modules: `import { ... } from './foo.js';`
  // and `import './foo.js';`. Multi-line imports are handled by matching
  // until the closing `;`.
  out = out.replace(/^\s*import\s+[^;]*?from\s+['"][^'"]+['"]\s*;?\s*$/gm, '');
  out = out.replace(/^\s*import\s+['"][^'"]+['"]\s*;?\s*$/gm, '');
  // Strip `export ` prefix on declarations: function, const, let, var, class.
  out = out.replace(/^\s*export\s+(?=(function|const|let|var|class|async\s+function)\b)/gm, '');
  // Disallow `export default` and `export { ... }` re-exports — they don't
  // make sense in a single concatenated scope. Fail loudly if encountered.
  if (/^\s*export\s+default\b/m.test(out)) {
    throw new Error('build: `export default` is not supported in src/ modules');
  }
  if (/^\s*export\s*\{/m.test(out)) {
    throw new Error('build: `export { ... }` is not supported in src/ modules');
  }
  return out;
}

function buildScriptBody() {
  const parts = [];
  parts.push('// AUTOGENERATED by build.mjs — do not hand-edit index.html.');
  parts.push('// Source of truth: src/*.js + src/template.html + src/styles.css');
  parts.push('');
  // Concatenate modules in dependency order. Missing modules are skipped
  // so early-epic builds still produce a working (if functionally empty)
  // page. prg-loader.js (regenerated above) carries the stub byte arrays
  // and lands in this loop like any other module.
  for (const name of MODULE_ORDER) {
    const path = join(SRC, name);
    if (!existsSync(path)) continue;
    parts.push(`// ----- ${name} -----`);
    parts.push(stripEsm(readText(path)).trimEnd());
    parts.push('');
  }
  return parts.join('\n');
}

function main() {
  // Sync prg-loader.js from the canonical .bin files before reading any
  // module source. Idempotent: if the .bin files haven't changed, the
  // output bytes are identical.
  regeneratePrgLoaderJs();

  const template = readText(join(SRC, 'template.html'));
  const styles = readText(join(SRC, 'styles.css'));
  const script = buildScriptBody();

  // Use the function form of String.replace so `$&`, `$'`, `$\``, `$1`
  // back-references in the replacement string are NOT interpreted —
  // critical because the script body can legitimately contain
  // sequences like `'$'` (e.g. formatAddr's return string).
  let out = template;
  out = out.replace('{{STYLES}}', () => styles.trimEnd());
  out = out.replace('{{SCRIPT}}', () => script.trimEnd());

  // Normalize to LF line endings; never embed timestamps or host paths.
  out = out.replace(/\r\n/g, '\n');
  if (!out.endsWith('\n')) out += '\n';

  writeFileSync(join(ROOT, 'index.html'), out);
  console.log(`build: index.html written (${out.length} bytes)`);
}

main();
